# Beggining of function, create obj "inv" and set it to NULL to avoid calling
# past values on matrix. Set function of matrix x, x is defined as a numeric
# matrix. A local value for x is generated where the get function would call
# later on the code. This is to avoid objects of x located in the global
# environment to be taken into the functions' calculations
makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
# For a matrix to get inversed, it has to meet the condition of being squared,
# where the # of columns is equal to the # of rows. Warning message is generated
# matrix x is set to NULL until this is corrected, x is defined in the parent
# environment for this purpose
        if(nrow(x) != ncol(x)) {
                message("matrix is not squared")
                message("matrix is not set in function")
                x <- NULL
        }
# functions for the x matrix and calculations for the inverse of the same matrix
# and storing are generated
        get <- function() x
        setinv <- function (solve) {
                inv <<- solve
                }
        getinv <- function () {
                inv
        }
# a list is generated for latter calls in the cacheSolve function
        list(set = set, get = get,
             setinv = setinv, getinv = getinv)
}

# cacheSolve function is initiated with matrix defined in makeCacheMatrix
cacheSolve <- function(x, ...) {
# An object is created "inv2" and call is generated from getinv
# function defined in makeCacheMatrix. Verification that matrix is not NULL
# is set in if condition
        inv2 <- x$getinv()
        if(!is.null(inv2)) {
                message("getting cached data")
                return(inv2)
        }
# datainv object is generated by calling the original matrix in MakeCacheMatrix
# Calculation of inverse of matrix is generated in inv2. Notice that in first
# iteration, inverse matrix is not calculated until now. The object x$getinv()
# remained as a NULL scalar on first call.
        datainv <- x$get()
        inv2 <- solve(datainv, ...)
# Inverse matrix is set in x$setinv() function
        x$setinv(inv2)
        inv2
# Print of inverse matrix is generated
}